development: &default
  adapter: postgresql
  database: orders_development
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000
  host: localhost
  username: postgres
  password: 1 

test:
  <<: *default
  database: orders_test

